# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgis/postgis:16-3.4-alpine 
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 54320:5432
 
